### PR TITLE
Add Spanish translation of the Standard criteria

### PR DESCRIPTION
**Pull request by AlbaRoza**
Includes:

- [x] Index
- [x] Readers guide
- [x] Glossary
- [x] CONTRIBUTING
- [x] GOVERNANCE
- [x] CHANGELOG
- [x] AUTHORS
- [x] print.htlm
- [x] Criteria:
    - [x] _template.md 
    - [x] Bundle policy and code
    - [x] Code in the open
    - [x] Continuous integration
    - [x] Document maturity
    - [x] Document objectives
    - [x] Document
    - [x] Index
    - [x] Make contributions easy
    - [x] Use open licenses
    - [x] Use open standards
    - [x] Open to contributions
    - [x] Require review
    - [x] Reusable and portable codebases
    - [x] Coherent style
    - [x] Understandable English first
    - [x] Version control and history

-----
[View rendered es/criterios/_plantilla.md](https://github.com/publiccodenet/community-translations-standard/blob/spanish-translation/es/criterios/_plantilla.md)
[View rendered es/criterios/codigo-en-abierto.md](https://github.com/publiccodenet/community-translations-standard/blob/spanish-translation/es/criterios/codigo-en-abierto.md)
[View rendered es/criterios/documentacion-madurez-codigo.md](https://github.com/publiccodenet/community-translations-standard/blob/spanish-translation/es/criterios/documentacion-madurez-codigo.md)
[View rendered es/criterios/integracion-continua.md](https://github.com/publiccodenet/community-translations-standard/blob/spanish-translation/es/criterios/integracion-continua.md)

### CODE REVIEW

**Comment by Ainali** [comment]
Nice work! The bulk is clearly done. There are a few more files needed in order for us to be able to generate a completely Spanish pdf. I have listed them in the readme under [Files to translate](https://github.com/publiccodenet/community-translations-standard#files-to-translate).

**Comment by maurosr** [comment]
Hi there! I gave this draft translations a read, as requested by @ericherman.

I think the main thing he wanted me to check was the "universality" of the Spanish and I have to say it is really, really good :) It is generally very neutral and I haven't seen any regional discrepancies, except perhaps some minor things, such as the article/gender used for certain english words (e.g. "la codebase" vs. "el codebase") but it is not something that would hurt readability of understanding of the concepts.
Also, it is very nice to include the original english word with the disjunction (o) when the translation is not very used and the english word can help clarify (e.g. "revisores o reviewers").
The translation of the requirement level words (MUST, SHOULD, MAY, etc.) is great and makes a lot of sense.
So, overall, IMHO there is nothing to be improved or fixed about the translation to Spanish.

That said, I did spot some errors while scanning through the text, but not in translation, they are either typos, or parts left in English by mistake, that will get fixed when doing a thorough read. The only case I think is worth mentioning because it could be hard to spot is https://github.com/publiccodenet/community-translations-standard/pull/3/files#diff-b017d8b25cc1272719652c26167ce14c5e30f8af7770100fccd6e57171e8ba20R11 where instead of "PUEDE" it should be "PODRIA" as the original in English is SHOULD.

I hope this helps :)

**Comment by AlbaRoza** [comment]
Thank you so much for your input @maurosr ! Applying some of the changes now!

**Review by ericherman — APPROVED** [review]
This has been removed from the orginal in the latest version, but was in the original for this version. That said, I am on-board with removing this because it looks like a translation error even though it is not.

**Pull request merged**
